import type { Metadata } from "next";
import "./globals.css";

import {
    Bebas_Neue,
    Oswald,
} from "next/font/google";

const bebas = Bebas_Neue({
    subsets: ["latin"],
    weight: "400",
});

const oswald = Oswald({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebas.className} ${oswald.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
